version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000/predict
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud:ro
    depends_on:
      - api
