version: 2

models:
  - name: stg_events
    description: "Cleaned staging view of the raw cosmetics events."
    columns:
      - name: event_time
        tests:
          - not_null
      - name: event_type
        tests:
          - not_null
          - accepted_values:
              values: ['cart', 'view', 'purchase', 'remove_from_cart']
      - name: user_id
        tests:
          - not_null
      - name: user_session
        tests:
          - not_null
